export class PrivilegePermissions {
  parent_id: number | null = null;
  permissions: string = "";
}

export namespace PrivilegePermissions {
  export enum PERMISSIONS {
    CAN_VIEW_ENTERPRISE = "CAN_VIEW_ENTERPRISE",
    CAN_VIEW_TEAMS = "CAN_VIEW_TEAM",
    CAN_VIEW_POINT_OF_CARE = "CAN_VIEW_POINT_OF_CARE",
    CAN_VIEW_REGISTERED_APPLICATIONS = "CAN_VIEW_REGD_APPLICATIONS",
    CAN_VIEW_SETTINGS = "CAN_VIEW_SETTINGS",
    CAN_VIEW_USER = "CAN_VIEW_USER",
    CAN_VIEW_ROLEPROFILE = "CAN_VIEW_ROLEPROFILE",
    CAN_MANAGE_ENTERPRISE = "CAN_MANAGE_ENTERPRISE",
    CAN_MANAGE_REGISTERED_APPLICATIONS = "CAN_MANAGE_REGD_APPLICATIONS",
    CAN_MANAGE_TEAM = "CAN_MANAGE_TEAM",
    CAN_MANAGE_POINT_OF_CARE = "CAN_MANAGE_POINT_OF_CARE",
    CAN_MANAGE_ESCALATION = "CAN_MANAGE_ESCALATION",
    CAN_VIEW_PASSWORD_POLICY = "CAN_VIEW_PASSWORD_POLICY",
    CAN_MANAGE_PASSWORD_POLICY = "CAN_MANAGE_PASSWORD_POLICY",
    CAN_MANAGE_SETTINGS = "CAN_MANAGE_SETTINGS",
    CAN_MANAGE_USER = "CAN_MANAGE_USER",
    CAN_DESIGN_ENTERPRISE_LAYOUT = "CAN_MANAGE_ENTERPRISE_LAYOUT",
    CAN_MANAGE_ROLEPROFILE = "CAN_MANAGE_ROLEPROFILE",
    // CAN_MANAGE_SETTINGS = "CAN_MANAGE_SETTINGS",
    // CAN_MANAGE_ACCESS_CONTROL = "CAN_MANAGE_ACCESS_CONTROL",
    // CAN_MANAGE_USER = "CAN_MANAGE_USER",
    // CAN_MANAGE_ROLEPROFILE = "CAN_MANAGE_ROLEPROFILE",
    // CAN_MANAGE_ENTERPRISE = "CAN_MANAGE_ENTERPRISE",
    // CAN_MANAGE_USERTEAM = "CAN_MANAGE_USERTEAM",
    // CAN_MANAGE_ALARM_ROUTING = "CAN_MANAGE_ALARM_ROUTING",
    // CAN_VIEW_ACCESS_CONTROL = "CAN_VIEW_ACCESS_CONTROL",
    // CAN_VIEW_USER = "CAN_VIEW_USER",
    // CAN_VIEW_ROLEPROFILE = "CAN_VIEW_ROLEPROFILE",
    // CAN_VIEW_SETTINGS = "CAN_VIEW_SETTINGS",
    // CAN_VIEW_ENTERPRISE = "CAN_VIEW_ENTERPRISE",
    // CAN_VIEW_USERTEAM = "CAN_VIEW_USERTEAM",
    // CAN_VIEW_ALARM_ROUTING = "CAN_VIEW_ALARM_ROUTING",
    // CAN_ALTER_USER_STATUS = "CAN_ALTER_USER_STATUS",
    // CAN_VIEW_ALL = "CAN_VIEW_ALL",
    // CAN_MODIFY_ALL = "CAN_MODIFY_ALL",
    // CAN_MANAGE_ALL = "CAN_MANAGE_ALL",
  }
  export enum PERMISSION_CHECK_MODE {
    SOME = "SOME",
    EVERY = "EVERY",
  }
}
